"""Canary Sweep — find which input fields STORE attacker text intact, before spending any payload.

WHY THIS EXISTS
  Hunt #37 mapped 1041 input fields and 176 usable payloads. Firing every payload at every field is
  ~35k requests: that is scanning, it is slow, and most of it teaches nothing because a field that
  coerces, truncates or rejects its input can never carry an injection anyway.

  So pass 1 sends ONE unique marker per field, grouped so a whole input object is written in a
  single request, then reads every field back and sorts them:

    STORED-INTACT   the marker came back byte-for-byte      -> pass 2 spends real payloads here
    TRANSFORMED     encoded, stripped, truncated, coerced   -> record what the transform was
    REJECTED        the write failed or the field is absent -> nothing to attack
    UNREADABLE      no read path for this field             -> never "clean", just unmeasured

  Two orders of magnitude fewer requests, and every result is readable.

THE RULE THIS ENFORCES
  A field is only sorted when it has a PROVEN READ PATH. Writing a marker you cannot read back is
  not a test — it is a write with no oracle, and counting it as covered is how a class gets marked
  green while untested. Families without a verified read query are emitted as UNREADABLE by
  construction, never omitted silently.

  Storage is a LEAD, not a verdict: a marker surviving intact says the value round-trips, NOT that
  it is injectable. Only a human seeing the rendered DOM closes an XSS.

Offline, stdlib-only. Generates a batch; sends nothing itself.
"""
import json
import os
import re
import sys

try:
    from . import schema_surface as ss
except ImportError:                                  # run as a script
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import schema_surface as ss

# Types whose values can carry text at all. A Rupee or Boolean field cannot hold a payload, so
# marking one is a wasted request — but its COERCION behaviour is still worth one probe, which is
# why the numeric families are listed separately rather than dropped.
TEXTUAL = {"String", "Byte"}
COERCING = {"Rupee", "Decimal", "Percent", "PreciseRupee", "MoneyEx", "Int", "Long",
            "DateTimeWrapper", "TimeStampWrapper", "FiscalYear"}

MARKER = "ZQ7X%sK3"          # unique per field, greppable, harmless

# Identity fields never receive a marker. Standing rule: no government ID goes into a target, and a
# marker in an identity slot risks creating a malformed identity record on a real tax product.
NEVER_MARK = {"pan", "aadhaarCardNumber", "enrollmentNumber", "tanOfEmployer",
              "directorIdentificationNumber", "ifscCode", "iFSCCode", "swiftCode"}


def fields_for(surface, input_name):
    """Every field of one INPUT_OBJECT, split into textual / coercing / other."""
    rows = [f for f in surface["inputs"] if f["input"] == input_name]
    out = {"textual": [], "coercing": [], "other": []}
    for f in rows:
        t = f["fieldType"]
        if t in TEXTUAL:
            out["textual"].append(f)
        elif t in COERCING:
            out["coercing"].append(f)
        else:
            out["other"].append(f)
    return out


def marker_object(split, base=None, include_coercing=False):
    """Build one input object with a unique marker in every textual field.

    Returns (obj, planted, skipped) — `skipped` names the identity fields deliberately left alone,
    so the coverage record shows them as excluded-by-policy rather than silently missing.
    """
    obj = dict(base or {})
    planted, skipped = {}, []
    for f in split["textual"]:
        name = f["field"]
        if name in NEVER_MARK:
            skipped.append(name)
            continue
        obj[name] = MARKER % name
        planted[name] = obj[name]
    if include_coercing:
        # A coercion probe, not an injection: does the parser accept text where a number belongs?
        for f in split["coercing"]:
            name = f["field"]
            if name in NEVER_MARK:
                skipped.append(name)
                continue
            obj[name] = MARKER % name
            planted[name] = obj[name]
    return obj, planted, skipped


JS = r"""// CANARY SWEEP pass 1 - generated by core/canary_sweep.py
// One unique marker per textual field, written in ONE request, then read back and sorted.
// Storage is a LEAD, not a verdict. Nothing here is an injection payload.
(async()=>{
  if(location.hostname!=='__HOST__'){console.error('run on __HOST__');return;}
  const V=__VARS__, PLANTED=__PLANTED__, BASE=__BASE__;
  const MUT=__MUT__, READ=__READ__;
  const gql=async(q,v)=>{
    const r=await fetch('/graphql',{method:'POST',credentials:'include',
      headers:{'content-type':'application/json','accept':'*/*','X-Comolho-Client':'kiran_kk'},
      body:JSON.stringify({query:q,variables:v})});
    const t=await r.text(); let d=null; try{d=JSON.parse(t)}catch{}
    return {s:r.status,d,t};
  };

  // 1. positive control: write the KNOWN-GOOD baseline first and read it back.
  const send=(obj)=>gql(MUT,{...V,__VARNAME__:obj});
  const c0=await send(BASE);
  const c1=await gql(READ,V);
  const dig=(r)=>{const be=r.d&&r.d.data&&r.d.data.user&&r.d.data.user.baseEntity; return __DIG__;};
  const ctrl=dig(c1);
  console.log('CONTROL write', c0.s, '| read', c1.s, '| baseline readable:', !!ctrl);
  if(!ctrl){console.error('CONTROL FAILED -> UNREADABLE, no verdict. Stopping.');return;}

  // 2. plant the markers
  const w=await send({...BASE,...PLANTED});
  console.log('MARKER write', w.s, w.d&&w.d.errors?JSON.stringify(w.d.errors).slice(0,200):'ok');

  // 3. read back and sort
  const after=dig(await gql(READ,V));
  const out={INTACT:[],TRANSFORMED:[],REJECTED:[],ABSENT:[]};
  for(const [name,sent] of Object.entries(PLANTED)){
    if(!after || !(name in after)){ out.ABSENT.push(name); continue; }
    const got=after[name];
    if(got===sent) out.INTACT.push(name);
    else if(got===null||got===''||got===undefined) out.REJECTED.push(name+' -> '+JSON.stringify(got));
    else out.TRANSFORMED.push(name+' : sent '+JSON.stringify(sent)+' got '+JSON.stringify(got));
  }
  console.log('=== INTACT      ('+out.INTACT.length+')', out.INTACT.join(', '));
  console.log('=== TRANSFORMED ('+out.TRANSFORMED.length+')'); out.TRANSFORMED.forEach(x=>console.log('   ',x));
  console.log('=== REJECTED    ('+out.REJECTED.length+')', out.REJECTED.join(', '));
  console.log('=== ABSENT      ('+out.ABSENT.length+')  <- no read path, UNREADABLE not clean');
  console.log('   ', out.ABSENT.join(', '));
  console.log('planted '+Object.keys(PLANTED).length+' markers');

  // 4. restore the baseline so the draft is left as found
  const r=await send(BASE);
  console.log('RESTORE', r.s);
  window.CANARY=out;
})();
"""


def build(surface, input_name, host, variables, mutation, read_query, base,
          include_coercing=False, var_name="input", dig="null"):
    """`var_name` = the GraphQL variable the input object rides in.
    `dig` = a JS expression over `be` (the baseEntity) returning the object to read fields back from.
    """
    split = fields_for(surface, input_name)
    obj, planted, skipped = marker_object(split, base=base, include_coercing=include_coercing)
    js = (JS.replace("__HOST__", host)
            .replace("__VARS__", json.dumps(variables))
            .replace("__PLANTED__", json.dumps(planted))
            .replace("__BASE__", json.dumps(base))
            .replace("__MUT__", json.dumps(mutation))
            .replace("__READ__", json.dumps(read_query))
            .replace("__VARNAME__", var_name)
            .replace("__DIG__", dig))
    return js, split, planted, skipped
