"""
Phase 21 — Echo Agent (real implementation)
LLM generates Python tool code → validates → registers into tools_registry.
"""

import os
import ast
import json
import re
import importlib
from core.llm import ask_llm

TOOLS_DIR = "data/generated_tools"
os.makedirs(TOOLS_DIR, exist_ok=True)

_SAFE_BUILTINS = {
    "print", "len", "range", "str", "int", "float", "bool", "list", "dict",
    "tuple", "set", "enumerate", "zip", "sorted", "reversed", "min", "max",
    "sum", "abs", "round", "isinstance", "type", "hasattr", "getattr",
    "Exception", "ValueError", "TypeError", "KeyError", "IndexError",
    "True", "False", "None",
}

_GEN_PROMPT = '''You are a Python code generator for JARVIS.
Generate a single Python function for this task: "{task}"

Function name: tool_{name}
Signature: def tool_{name}(parameters: dict) -> dict:
Return format: {{"success": True/False, "message": "...", "data": {{...}}}}

Rules:
- Use only Python stdlib (os, subprocess, datetime, json, re, math, pathlib, etc.)
- Add imports inside the function body
- Handle all errors with try/except, return {{"success": False, "message": str(e), "data": {{}}}}
- Extract inputs from parameters dict with .get()
- Return useful info in "data" key

Generate ONLY the function code. No class. No explanation. No markdown fences.

def tool_{name}(parameters: dict) -> dict:'''


class GeneratedTool:
    """Wrapper that makes a generated function look like an agent."""

    def __init__(self, name: str, func):
        self.name = name
        self._func = func

    def run(self, input_text: str = "", action: str = None, parameters: dict = None) -> dict:
        parameters = parameters or {}
        # Accept any action name or None — generated tools have one thing they do
        try:
            return self._func(parameters)
        except Exception as e:
            return {"success": False, "message": f"Tool '{self.name}' error: {e}", "data": {}}


class EchoAgent:

    def __init__(self):
        self._load_all()

    # ─────────────────────────────────────────
    # LOAD SAVED TOOLS ON STARTUP
    # ─────────────────────────────────────────
    def _load_all(self):
        try:
            from core.tools_registry import register_tool
        except ImportError:
            return  # tools_registry not ready yet (circular import during init)

        for fname in os.listdir(TOOLS_DIR):
            if not fname.endswith(".py"):
                continue
            name = fname[:-3]
            try:
                tool = self._load_from_file(name)
                if tool:
                    register_tool(name, tool)
                    print(f"[echo] Loaded generated tool: {name}")
            except Exception as e:
                print(f"[echo] Failed to load {name}: {e}")

    # ─────────────────────────────────────────
    # GENERATE TOOL
    # ─────────────────────────────────────────
    def generate_tool(self, task: str, tool_name: str = "") -> dict:
        if not task:
            return {"success": False, "message": "No task description provided.", "data": {}}

        # Derive clean tool name
        if not tool_name:
            tool_name = re.sub(r"[^a-z0-9]+", "_", task.lower().strip())[:24].strip("_")
        tool_name = re.sub(r"[^a-z0-9_]", "", tool_name.lower())

        if not tool_name:
            tool_name = "custom_tool"

        prompt = _GEN_PROMPT.format(task=task, name=tool_name)

        raw = ask_llm(prompt)
        if not raw:
            return {"success": False, "message": "LLM returned nothing.", "data": {}}

        # Strip markdown fences if present
        raw = re.sub(r"```(?:python)?", "", raw).strip()

        # Prepend function def if LLM stripped it
        func_def = f"def tool_{tool_name}(parameters: dict) -> dict:"
        if not raw.startswith("def "):
            raw = func_def + "\n" + raw

        # Validate syntax
        try:
            ast.parse(raw)
        except SyntaxError as e:
            return {
                "success": False,
                "message": f"Generated code has syntax error: {e}",
                "data": {"code": raw}
            }

        # Save to file
        fpath = os.path.join(TOOLS_DIR, f"{tool_name}.py")
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(f"# Generated by Echo Agent\n# Task: {task}\n\n{raw}\n")

        # Load and register
        tool = self._load_from_file(tool_name)
        if not tool:
            return {"success": False, "message": "Code saved but failed to load.", "data": {"code": raw}}

        try:
            from core.tools_registry import register_tool
            register_tool(tool_name, tool)
        except Exception as e:
            return {"success": False, "message": f"Registered failed: {e}", "data": {}}

        return {
            "success": True,
            "message": f"Tool '{tool_name}' created and registered. Say 'run tool {tool_name}' to use it.",
            "data": {"name": tool_name, "code": raw}
        }

    # ─────────────────────────────────────────
    # LOAD FROM FILE
    # ─────────────────────────────────────────
    def _load_from_file(self, name: str):
        fpath = os.path.join(TOOLS_DIR, f"{name}.py")
        if not os.path.exists(fpath):
            return None

        with open(fpath, "r", encoding="utf-8") as f:
            code = f.read()

        namespace = {}
        try:
            exec(compile(code, fpath, "exec"), namespace)
        except Exception as e:
            print(f"[echo] exec error for {name}: {e}")
            return None

        func = namespace.get(f"tool_{name}")
        if not callable(func):
            print(f"[echo] tool_{name} not found in namespace")
            return None

        return GeneratedTool(name, func)

    # ─────────────────────────────────────────
    # LIST TOOLS
    # ─────────────────────────────────────────
    def list_tools(self) -> dict:
        tools = [f[:-3] for f in os.listdir(TOOLS_DIR) if f.endswith(".py")]
        if not tools:
            return {"success": True, "message": "No generated tools yet. Say 'create a tool that...' to build one.", "data": {}}
        names = "\n".join(f"  • {t}" for t in tools)
        return {"success": True, "message": f"Generated tools ({len(tools)}):\n{names}", "data": {"tools": tools}}

    # ─────────────────────────────────────────
    # RUN TOOL BY NAME
    # ─────────────────────────────────────────
    def run_tool(self, name: str, parameters: dict = None) -> dict:
        tool = self._load_from_file(name)
        if not tool:
            return {"success": False, "message": f"Tool '{name}' not found.", "data": {}}
        return tool.run(parameters=parameters or {})

    # ─────────────────────────────────────────
    # DELETE TOOL
    # ─────────────────────────────────────────
    def delete_tool(self, name: str) -> dict:
        fpath = os.path.join(TOOLS_DIR, f"{name}.py")
        if not os.path.exists(fpath):
            return {"success": False, "message": f"Tool '{name}' not found.", "data": {}}

        os.remove(fpath)

        try:
            from core.tools_registry import unregister_tool
            unregister_tool(name)
        except Exception:
            pass

        return {"success": True, "message": f"Tool '{name}' deleted.", "data": {}}

    # ─────────────────────────────────────────
    # STANDARD RUN
    # ─────────────────────────────────────────
    def run(self, input_text: str = "", action: str = None, parameters: dict = None) -> dict:
        parameters = parameters or {}

        if action == "generate_tool":
            return self.generate_tool(
                task=parameters.get("task", input_text),
                tool_name=parameters.get("tool_name", "")
            )

        if action == "list_tools":
            return self.list_tools()

        if action == "run_tool":
            return self.run_tool(
                name=parameters.get("name", ""),
                parameters=parameters.get("parameters", {})
            )

        if action == "delete_tool":
            return self.delete_tool(name=parameters.get("name", ""))

        return {"success": False, "message": f"Unknown Echo action: {action}", "data": {}}


echo_agent = EchoAgent()
