#!/usr/bin/env python3
"""Generate .hunt_targets from the private registry, and prove the corpus is complete.

Why this exists. The disclosure guard reported "clean, 72 target names checked" while being
structurally unable to see three live programmes - one of them invite-only under strict
coordinated disclosure. The hook was not lying. It was reporting that nothing matched its
detection universe, and that universe was a hand-edited flat file nobody had updated.

    "N names checked" must mean the input set was complete and current,
    not that N names happened to sit in a stale file.

So the corpus becomes a GENERATED artefact with a provenance header carrying the hash of the
registry that produced it. prepush_scan refuses to run against a corpus whose hash does not
match, which turns "someone forgot to add a programme" from an invisible gap into a blocked push.

    python scripts/gen_hunt_targets.py              # regenerate
    python scripts/gen_hunt_targets.py --check      # verify freshness, write nothing
    python scripts/gen_hunt_targets.py --self-test  # prove the detector actually detects

Registry (data/targets.json, gitignored) is the authority. .hunt_targets is derived and must
never be hand-edited: an edit there is silently discarded on the next regeneration.
"""
import json
import io
import os
import sys
import hashlib
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "data", "targets.json")
CORPUS = os.path.join(ROOT, ".hunt_targets")
HDR = "# registry-sha256: "


def registry_hash(path=REGISTRY):
    """Hash the MEANING, not the file bytes - reformatting the json must not look like a change."""
    with io.open(path, encoding="utf-8") as f:
        reg = json.load(f)
    canon = json.dumps(reg.get("programmes", []), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()


def names_from_registry(path=REGISTRY):
    """Every leak shape for every ENABLED programme: its name plus every declared alias.

    Names shorter than 3 chars are dropped - they are substrings of ordinary words and would
    make the guard fire constantly, which is how a guard gets bypassed.
    """
    with io.open(path, encoding="utf-8") as f:
        reg = json.load(f)
    out = []
    for p in reg.get("programmes", []):
        if not p.get("enabled", True):
            continue
        for n in [p.get("name", "")] + list(p.get("aliases") or []):
            n = (n or "").strip()
            if len(n) >= 3:
                out.append(n)
    seen, uniq = set(), []
    for n in out:
        if n.lower() not in seen:
            seen.add(n.lower())
            uniq.append(n)
    return uniq


def write_corpus():
    h, names = registry_hash(), names_from_registry()
    with io.open(CORPUS, "w", encoding="utf-8", newline="\n") as f:
        f.write("# GENERATED by scripts/gen_hunt_targets.py - DO NOT HAND-EDIT.\n")
        f.write("# Hand edits are discarded on regeneration; add the programme to the registry.\n")
        f.write(HDR + h + "\n")
        for n in names:
            f.write(n + "\n")
    return h, len(names)


def check():
    """-> (ok, message). Fail-CLOSED: anything we cannot verify is a failure, because the cost
    is asymmetric - a false alarm costs a regeneration, a miss is a permanent public disclosure
    against a programme that forbids it.

    The bug this replaces: the scanner read the corpus with a plain "if not exists: return []",
    so a missing corpus meant zero names, the credential patterns still ran, and the scan exited
    0 reporting CLEAN. Fail-open on the half of the guard that matters most.
    """
    if not os.path.exists(REGISTRY):
        return False, "registry absent (data/targets.json) - cannot verify the name corpus is complete"
    if not os.path.exists(CORPUS):
        return False, "corpus absent (.hunt_targets) - run gen_hunt_targets.py"
    want = registry_hash()
    got = ""
    for ln in io.open(CORPUS, encoding="utf-8", errors="replace"):
        if ln.startswith(HDR):
            got = ln[len(HDR):].strip()
            break
    if not got:
        return False, "corpus carries no provenance header - it predates generation, regenerate it"
    if got != want:
        return False, ("corpus is STALE: registry sha256 %s, corpus says %s - regenerate"
                       % (want[:12], got[:12]))

    # The header alone is not enough. First version compared ONLY the header hash, so
    # truncating the body left the header intact and the check passed - the file claimed
    # to be the corpus while contributing nothing. Verify the BODY is exactly what the
    # registry would generate.
    body = [ln.strip() for ln in io.open(CORPUS, encoding="utf-8", errors="replace")
            if ln.strip() and not ln.startswith("#")]
    want_body = names_from_registry()
    if body != want_body:
        extra = len(set(b.lower() for b in body) - set(w.lower() for w in want_body))
        absent = len(set(w.lower() for w in want_body) - set(b.lower() for b in body))
        return False, ("corpus body does not match the registry: %d name(s) missing, %d unknown "
                       "(hand-edited?) - regenerate" % (absent, extra))
    # Completeness. Everything above proves the corpus matches the REGISTRY; none of it
    # proves the registry matches reality. A programme hunted but never registered hashes
    # consistently and passes every check - the same blind spot one level up.
    #
    # The invariant that is actually mechanical: a hunt leaves artefact directories on
    # disk, so anything with one must be registered. Starting a hunt without registering
    # it now blocks the next push instead of going unnoticed for weeks.
    unreg = unregistered_hunt_dirs()
    if unreg:
        # Printed by name on purpose: this output is a local hook message, never published,
        # and the operator cannot act on a count.
        return False, ("%d hunt artefact director%s on disk with no registry entry, "
                       "register then regenerate: %s"
                       % (len(unreg), "y" if len(unreg) == 1 else "ies",
                          ", ".join(sorted(d[0] for d in unreg))))

    return True, "corpus current: %d names, body verified, %d artefact dir(s) all registered" % (
        len(want_body), _artefact_dir_count())


_ARTEFACT_ROOTS = ("workspace/coverage", "workspace/scratch", "workspace/bundles")


def _artefact_dirs():
    """Directory names under the hunt artefact roots. Leading-underscore dirs are tooling
    (_tools, _scripts, _screening), not programmes."""
    found = set()
    for rel in _ARTEFACT_ROOTS:
        d = os.path.join(ROOT, *rel.split("/"))
        if not os.path.isdir(d):
            continue
        for name in os.listdir(d):
            if os.path.isdir(os.path.join(d, name)) and not name.startswith("_"):
                found.add(name)
    return found


def _artefact_dir_count():
    return len(_artefact_dirs())


def unregistered_hunt_dirs():
    """-> [(dirname, root)] for artefact dirs with no registry entry under any spelling."""
    known = set()
    for n in names_from_registry():
        low = n.lower()
        known.update({low, low.replace("-", ""), low.replace("-", "_"),
                      low.replace("_", ""), low.replace("_", "-")})
    out = []
    for name in sorted(_artefact_dirs()):
        low = name.lower()
        variants = {low, low.replace("-", ""), low.replace("-", "_"),
                    low.replace("_", ""), low.replace("_", "-")}
        if not (variants & known):
            out.append((name, "artefact dir"))
    return out


# ---------------------------------------------------------------- self-test
# An instrument that cannot fail its own positive control cannot issue a trusted
# negative (pb0767). These assertions drive the detector prepush_scan actually
# uses, not a reimplementation - a second copy of the regex would only prove the
# copy works.
_SHAPES = [
    "Hunting {n} now",
    "{n}.example.com",
    "{n}-staging",
    "/{n}/report",
    '"{n}"',
    "({n})",
    "{n} scope notes",
]


def self_test():
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import prepush_scan

    def detects(name, text):
        diff = "+++ b/some/file.md\n+" + text + "\n"
        return bool(prepush_scan.scan(diff, [name]))

    names = names_from_registry()
    results = []

    # 1. every configured target detected in its plain form. The absence of this
    #    check is what let three live programmes stay invisible.
    missing = [n for n in names if not detects(n, "we hunted %s today" % n)]
    results.append(("every configured target detected",
                    "%d/%d" % (len(names) - len(missing), len(names)), not missing))

    # 2. real leak shapes, not merely the bare word
    probe = names[0] if names else ""
    bad = [s for s in _SHAPES if probe and not detects(probe, s.format(n=probe))]
    results.append(("leak shapes detected (dotted/hyphenated/quoted/path)",
                    "%d/%d" % (len(_SHAPES) - len(bad), len(_SHAPES)), not bad))

    # 3. a fictional name is detected when configured
    fict = "zqcorpfictional"
    results.append(("fictional configured name detected", "1/1",
                    detects(fict, "escalate to %s security" % fict)))

    # 4. and must NOT fire glued inside an ordinary word. Short names are
    #    substrings of real words; this exact shape blocked a push once.
    results.append(("glued substring NOT a false positive", "quixo vs quixotic",
                    not detects("quixo", "that plan was quixotic at best")))

    # 5. an unconfigured name must not be detected - proves detection comes from
    #    the corpus rather than something accidentally hardcoded
    results.append(("unconfigured name not detected", "1/1",
                    not detects(fict, "nothing about zqcotherfiction here")))

    # 6. public fixtures must carry no real programme name. Fixtures are published.
    offenders = []
    for dirpath, _, filenames in os.walk(os.path.join(ROOT, "fixtures")):
        for fn in filenames:
            fp = os.path.join(dirpath, fn)
            try:
                txt = io.open(fp, encoding="utf-8", errors="replace").read()
            except OSError:
                continue
            for n in names:
                if re.search(r"(?<![A-Za-z0-9])" + re.escape(n) + r"(?![A-Za-z0-9])", txt, re.I):
                    offenders.append(os.path.relpath(fp, ROOT))
                    break
    results.append(("no real programme name in public fixtures",
                    "%d offending file(s)" % len(offenders), not offenders))

    failed = 0
    print("=== disclosure corpus self-test")
    for label, detail, ok in results:
        print("  %-52s %-24s %s" % (label, detail, "PASS" if ok else "FAIL"))
        if not ok:
            failed += 1
    if missing:
        print("  NOT DETECTED: %d name(s) - inspect the registry, names are not printed here" % len(missing))
    if offenders:
        print("  offending fixtures: %s" % ", ".join(sorted(set(offenders))[:10]))
    print("  -> %d/%d checks passed" % (len(results) - failed, len(results)))
    return failed == 0


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if arg == "--check":
        ok, msg = check()
        print(("OK: " if ok else "FAIL: ") + msg)
        return 0 if ok else 1
    if arg == "--self-test":
        return 0 if self_test() else 1
    h, n = write_corpus()
    print("wrote .hunt_targets: %d names, registry sha256 %s" % (n, h[:12]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
